name: Expire Stale Check-ins

on:
 schedule:
  - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  run-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Call Expire Checkins API
        run: |
          curl -X POST https://overhere2.vercel.app/api/cron/expire-checkins \
            -H "Authorization: Bearer ${{ secrets.CRON_API_TOKEN }}"
